insert into specialties (name) values
  ('Internal Medicine'),
  ('Cardiology'),
  ('Interventional Cardiology'),
  ('Cardiothoracic Surgery'),
  ('Neurology'),
  ('Neurosurgery'),
  ('Oncology'),
  ('General Surgery'),
  ('Gynecology & Obstetrics'),
  ('Pediatrics'),
  ('Pediatric Surgery'),
  ('Pediatric Cardiology'),
  ('Neonatal Intensive Care'),
  ('Dermatology'),
  ('ENT (Ear, Nose & Throat)'),
  ('Gastroenterology'),
  ('Hematology'),
  ('Infectious Diseases'),
  ('Nephrology'),
  ('Orthopedics'),
  ('Plastic Surgery'),
  ('Psychiatry'),
  ('Pulmonology'),
  ('Urology');
